"""Core Incus operations for local chatmail LXC containers."""

import json
import subprocess
import textwrap
import time
from pathlib import Path

from ..util import shell

LABEL_KEY = "user.localchat-managed"
SSH_KEY_NAME = "id_localchat"
DOMAIN_SUFFIX = ".localchat"
UPSTREAM_IMAGE = "images:debian/12"
BASE_IMAGE_ALIAS = "localchat-base"
BASE_SETUP_NAME = "localchat-base-setup"
RELAY_IMAGE_ALIAS = "localchat-relay"

DNS_CONTAINER_NAME = "ns-localchat"
DNS_DOMAIN = "ns.localchat"


class DNSConfigurationError(Exception):
    """Raised when the DNS container is not reachable or not answering."""


def _extract_ip(net_data, family="inet"):
    """Extract the first global-scope IP of *family* from network state data.

    *net_data* is the ``state.network`` dict from ``incus list --format=json``.
    *family* is ``"inet"`` for IPv4 or ``"inet6"`` for IPv6.
    Returns the address string, or None.
    """
    for iface_name, iface in net_data.items():
        if iface_name == "lo":
            continue
        for addr in iface.get("addresses", []):
            if addr["family"] == family and addr["scope"] == "global":
                return addr["address"]
    return None


class Incus:
    """Gateway for all Incus container operations.

    Instantiated once per CLI command and passed around so that
    all modules share a single entry point for Incus interactions.
    """

    def __init__(self, out):
        self.out = out
        self.project_root = Path(__file__).resolve().parent.parent.parent.parent.parent
        self.lxconfigs_dir = self.project_root / "lxconfigs"
        self.lxconfigs_dir.mkdir(exist_ok=True)
        self.ssh_key_path = self.lxconfigs_dir / SSH_KEY_NAME
        if not self.ssh_key_path.exists():
            shell(
                f"ssh-keygen -t ed25519 -f {self.ssh_key_path} -N '' -C localchat",
                check=True,
            )
        self.ssh_config_path = self.lxconfigs_dir / "ssh-config"

    def write_ssh_config(self):
        """Write ``lxconfigs/ssh-config`` mapping all containers to their IPs.

        Each Host block maps the container name, the domain name, and the
        short relay name (e.g. ``_test0``) to the container's IP, using the
        shared localchat SSH key.  Returns the path to the file.
        """
        containers = self.list_managed()
        key_path = self.ssh_key_path
        lines = ["# Auto-generated by cmdeploy lxc-start — do not edit\n"]
        for c in containers:
            hosts = [c["name"]]
            domain = c.get("domain", "")
            if domain and domain != c["name"]:
                hosts.append(domain)
                short = domain.split(".")[0]
                if short and short not in hosts:
                    hosts.append(short)
            lines.append(f"\nHost {' '.join(hosts)}\n")
            lines.append(f"    Hostname {c['ip']}\n")
            lines.append("    User root\n")
            lines.append(f"    IdentityFile {key_path}\n")
            lines.append("    IdentitiesOnly yes\n")
            lines.append("    StrictHostKeyChecking accept-new\n")
            lines.append("    UserKnownHostsFile /dev/null\n")
            lines.append("    LogLevel ERROR\n")
        path = self.ssh_config_path
        path.write_text("".join(lines))
        return path

    def check_ssh_include(self):
        """Check if the user's ~/.ssh/config already includes our ssh-config."""
        user_ssh_config = Path.home() / ".ssh" / "config"
        if not user_ssh_config.exists():
            return False
        lines = user_ssh_config.read_text().splitlines()
        target = f"include {self.ssh_config_path}".lower()
        return any(line.strip().lower() == target for line in lines)

    def run(self, args, check=True, capture=True, input=None):
        """Run an incus command.

        When *capture* is True and *verbosity* >= 1, output is streamed
        to the terminal line-by-line while also being captured for
        later return via result.stdout.
        """
        cmd = ["incus"] + list(args)
        sub = self.out.new_prefixed_out("  ")

        if not capture:
            # Simple case: let subprocess handle streams (no capture)
            if self.out.verbosity >= 1:
                sub.print(f"$ {' '.join(cmd)}")
            return subprocess.run(
                cmd, text=True, input=input, check=check, stdout=None, stderr=None
            )

        # Capture case: we may need to stream while capturing
        if sub.verbosity >= 1:
            cmd_lines = " ".join(cmd).splitlines()
            sub.print(f"$ {cmd_lines.pop(0)}")
            if sub.verbosity >= 2:
                for line in cmd_lines:
                    sub.print(f"  {line}")

        proc = subprocess.Popen(
            cmd,
            text=True,
            stdin=subprocess.PIPE if input else None,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )

        stdout_lines = []
        if input:
            proc.stdin.write(input)
            proc.stdin.close()

        for line in proc.stdout:
            stdout_lines.append(line)
            if sub.verbosity >= 2:
                sub.print(f"  > {line.rstrip()}")

        ret = proc.wait()
        stdout = "".join(stdout_lines)
        if check and ret != 0:
            for line in stdout.splitlines():
                if sub.verbosity < 1:  # and we haven't printed it yet
                    sub.red(line)
            raise subprocess.CalledProcessError(ret, cmd, output=stdout)

        return subprocess.CompletedProcess(cmd, ret, stdout=stdout)

    def run_json(self, args, check=True):
        """Run an incus command with ``--format=json``.

        Returns the parsed JSON on success.
        When *check* is True raises ``subprocess.CalledProcessError``
        on non-zero exit; when False returns *None* instead.
        """
        result = self.run(
            list(args) + ["--format=json"],
            check=check,
        )
        if result.returncode != 0:
            return None
        return json.loads(result.stdout)

    def run_output(self, args, check=True):
        """Run an incus command and return its stripped stdout.

        When *check* is False, returns *None* on non-zero exit
        instead of raising.
        """
        result = self.run(args, check=check)
        if result.returncode != 0:
            return None
        return result.stdout.strip()

    def find_image(self, aliases):
        """Return the first alias from *aliases* that exists, else None."""
        images = self.run_json(["image", "list"], check=False) or []
        existing = {a.get("name") for img in images for a in img.get("aliases", [])}
        for alias in aliases:
            if alias in existing:
                return alias
        return None

    def delete_images(self):
        """Delete the cached base and relay images."""
        for alias in (RELAY_IMAGE_ALIAS, BASE_IMAGE_ALIAS):
            self.run(["image", "delete", alias], check=False)  # ok if absent

    def list_managed(self):
        """Return list of dicts with name, ip, ipv6, domain, status, memory_usage."""
        containers = []
        for ct in self.run_json(["list"]):
            config = ct.get("config", {})
            if config.get(LABEL_KEY) != "true":
                continue
            name = ct["name"]
            state = ct.get("state", {})
            net = state.get("network") or {}
            containers.append(
                {
                    "name": name,
                    "ip": _extract_ip(net, "inet"),
                    "ipv6": _extract_ip(net, "inet6"),
                    "domain": config.get(
                        "user.localchat-domain", f"{name}{DOMAIN_SUFFIX}"
                    ),
                    "status": ct.get("status", "Unknown"),
                    "memory_usage": state.get("memory", {}).get("usage", 0),
                }
            )
        return containers

    def ensure_base_image(self):
        """Build and cache a base image with openssh and the SSH key.

        The image is published as a local incus image with alias
        'localchat-base'.  Subsequent container launches use this
        image instead of the upstream Debian 12, skipping the
        slow apt-get install step.
        Returns the image alias.
        """
        if self.find_image([BASE_IMAGE_ALIAS]):
            self.out.print(f"  Base image '{BASE_IMAGE_ALIAS}' already cached.")
            return BASE_IMAGE_ALIAS

        self.out.print("  Building base image (one-time setup) ...")

        self.run(["delete", BASE_SETUP_NAME, "--force"], check=False)
        self.run(["image", "delete", BASE_IMAGE_ALIAS], check=False)
        self.run(["launch", UPSTREAM_IMAGE, BASE_SETUP_NAME])

        ct = Container(self, BASE_SETUP_NAME)
        ct.wait_ready()

        key_path = self.ssh_key_path
        pub_key = key_path.with_suffix(".pub").read_text().strip()
        ct.bash(f"""
            echo 'nameserver 9.9.9.9' > /etc/resolv.conf
            apt-get -o DPkg::Lock::Timeout=60 update
            DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server python3
            systemctl enable ssh
            apt-get clean
            mkdir -p /root/.ssh
            chmod 700 /root/.ssh
            echo '{pub_key}' > /root/.ssh/authorized_keys
            chmod 600 /root/.ssh/authorized_keys
        """)

        self.run(["stop", BASE_SETUP_NAME])
        self.run(["publish", BASE_SETUP_NAME, f"--alias={BASE_IMAGE_ALIAS}"])
        self.run(["delete", BASE_SETUP_NAME, "--force"])
        self.out.print(f"  Base image '{BASE_IMAGE_ALIAS}' ready.")
        return BASE_IMAGE_ALIAS

    def get_container(self, name):
        """Return a container handle for the given name.

        Accepts both short relay names (``test0``) and full Incus
        container names (``test0-localchat``).  Returns
        ``DNSContainer`` for the DNS container and
        ``RelayContainer`` for everything else.
        """
        if name == DNS_CONTAINER_NAME:
            return DNSContainer(self)
        return RelayContainer(self, name.removesuffix("-localchat"))

    def get_dns_container(self):
        """Return a DNSContainer handle."""
        return DNSContainer(self)


class Container:
    """The base container handle wraps all interactions with incus."""

    def __init__(self, incus, name, domain=None, memory="200MiB"):
        self.incus = incus
        self.out = incus.out
        self.name = name
        self.domain = domain or f"{name}{DOMAIN_SUFFIX}"
        self.memory = memory
        self.ipv4 = None
        self.ipv6 = None

    def bash(self, script, check=True):
        """Returns stdout from executing ``bash -ec <script>`` inside this container.

        *script* is dedented and stripped so callers can use triple-quoted strings.
        When *check* is False, returns *None* on non-zero exit instead of raising.
        """
        script = textwrap.dedent(script).strip()
        cmd = ["exec", self.name, "--", "bash", "-ec", script]
        return self.incus.run_output(cmd, check=check)

    def run_cmd(self, *args, check=True):
        """Return stdout from running a command directly in the container (no shell).

        When *check* is False, returns *None* on non-zero exit instead of raising.
        """
        return self.incus.run_output(
            ["exec", self.name, "--", *args],
            check=check,
        )

    def start(self):
        self.incus.run(["start", self.name])

    def stop(self, force=False):
        cmd = ["stop", self.name]
        if force:
            cmd.append("--force")
        self.incus.run(cmd, check=False)

    def launch(self):
        """Launch from the best available image, return the alias used."""
        image = self.incus.find_image([RELAY_IMAGE_ALIAS, BASE_IMAGE_ALIAS])
        if not image:
            raise RuntimeError(
                f"No base image '{BASE_IMAGE_ALIAS}' found. "
                "Call ensure_base_image() before launching containers."
            )
        self.out.print(f"  Launching from '{image}' image ...")
        cfg = []
        cfg += ("-c", f"{LABEL_KEY}=true")
        cfg += ("-c", f"user.localchat-domain={self.domain}")
        cfg += ("-c", f"limits.memory={self.memory}")
        self.incus.run(["launch", image, self.name, *cfg])
        return image

    def ensure(self):
        """Create/start this container from the cached base image.

        On first call, builds the base image (~30s).
        Subsequent containers launch in ~2s from the cached image.
        Returns ``self`` for chaining.
        """
        data = self.incus.run_json(["list", self.name], check=False) or []

        existing = [c for c in data if c["name"] == self.name]
        if existing:
            if existing[0]["status"] != "Running":
                self.start()
        else:
            self.launch()
        self.wait_ready()
        return self

    def destroy(self):
        """Stop, delete, and clean up config files."""
        self.stop(force=True)
        self.incus.run(["delete", self.name, "--force"], check=False)

    def push_file_content(self, dest_path, content):
        """Write *content* to *dest_path* inside the container.

        *content* is dedented and stripped so callers can use
        indented triple-quoted strings.
        """
        content = textwrap.dedent(content).strip() + "\n"
        self.incus.run(
            ["file", "push", "-", f"{self.name}{dest_path}"],
            input=content,
        )
        self.bash(f"chmod 644 {dest_path}")

    def wait_ready(self, timeout=60):
        """Wait until the container is running with an IPv4 address.

        Sets ``self.ipv4`` and ``self.ipv6`` (may be *None*),
        or raises ``TimeoutError``.
        """
        deadline = time.time() + timeout
        while time.time() < deadline:
            data = self.incus.run_json(
                ["list", self.name],
                check=False,
            )
            if data and data[0].get("status") == "Running":
                net = data[0].get("state", {}).get("network", {})
                self.ipv4 = _extract_ip(net, "inet")
                self.ipv6 = _extract_ip(net, "inet6")
                if self.ipv4:
                    return
            time.sleep(1)
        raise TimeoutError(
            f"Container {self.name!r} did not become ready within {timeout}s"
        )

    def rss_mib(self):
        """Return ``(used, total)`` memory from container (or None if unobtainable)."""
        output = self.bash("free -m", check=False)
        if output:
            for line in output.splitlines():
                if line.startswith("Mem:"):
                    parts = line.split()
                    return int(parts[2]), int(parts[1])


class RelayContainer(Container):
    """Container handle for a chatmail relay.

    Accepts the short relay name (e.g. ``test0``) and derives
    the Incus container name and mail domain automatically.
    """

    def __init__(self, incus, name):
        super().__init__(
            incus,
            f"{name}-localchat",
            domain=f"_{name}{DOMAIN_SUFFIX}",
            memory="600MiB",
        )
        self.sname = name
        self.ini = incus.lxconfigs_dir / f"chatmail-{name}.ini"
        self.zone = incus.lxconfigs_dir / f"{name}.zone"

    def launch(self):
        """Launch (from a potentially cached image) and clear inherited chatmail-version."""
        image = super().launch()
        self.bash("rm -f /etc/chatmail-version")
        return image

    def destroy(self):
        """Stop, delete, and clean up config files."""
        super().destroy()
        if self.ini.exists():
            self.ini.unlink()

    def disable_ipv6(self):
        """Disable IPv6 inside the container via sysctl."""
        # incus provides net.* virtualization for LXC containers so that
        # these sysctls only affect the container's network namespace.
        self.bash("""
            sysctl -w net.ipv6.conf.all.disable_ipv6=1
            sysctl -w net.ipv6.conf.default.disable_ipv6=1
            mkdir -p /etc/sysctl.d
            printf 'net.ipv6.conf.all.disable_ipv6=1\\n
            net.ipv6.conf.default.disable_ipv6=1\\n'
            > /etc/sysctl.d/99-disable-ipv6.conf
        """)

    def configure_hosts(self, ip):
        """Set hostname and /etc/hosts inside the container."""
        self.bash(f"""
            echo '{self.name}' > /etc/hostname
            hostname {self.name}
            sed -i '/ {self.domain}$/d' /etc/hosts
            echo '{ip} {self.name} {self.domain}' >> /etc/hosts
        """)

    def publish_as_relay_image(self):
        """Publish this container as a reusable relay image.

        Stops the container, 'publishes' it as 'localchat-relay', then restarts it.
        """
        if self.incus.find_image([RELAY_IMAGE_ALIAS]):
            return
        self.out.print(
            f"  Locally caching {self.name!r} as '{RELAY_IMAGE_ALIAS}' image ..."
        )
        self.incus.run(
            ["publish", self.name, f"--alias={RELAY_IMAGE_ALIAS}", "--force"]
        )
        self.wait_ready()
        self.out.print(f"  Relay image '{RELAY_IMAGE_ALIAS}' ready.")

    def deployed_version(self):
        """Read /etc/chatmail-version, or None if absent."""
        return self.bash("cat /etc/chatmail-version", check=False)

    def deployed_domain(self):
        """Read the domain deployed on the container (postfix myhostname)."""
        return self.bash(
            "postconf -h myhostname 2>/dev/null",
            check=False,
        )

    def verify_ssh(self, ssh_config):
        """Verify SSH connectivity to this container."""
        cmd = f"ssh -F {ssh_config} -o ConnectTimeout=60 root@{self.domain} hostname"
        return shell(cmd, timeout=60).returncode == 0

    def configure_dns(self, dns_ip):
        """Point this container's resolver at *dns_ip* and verify DNS is reachable."""
        self.bash(f"""
            systemctl disable --now systemd-resolved 2>/dev/null || true
            rm -f /etc/resolv.conf
            echo 'nameserver {dns_ip}' > /etc/resolv.conf
            mkdir -p /etc/unbound/unbound.conf.d
            printf 'server:\\n  domain-insecure: "localchat"\\n\\n
            forward-zone:\\n  name: "localchat"\\n
              forward-addr: {dns_ip}\\n'
            > /etc/unbound/unbound.conf.d/localchat-forward.conf
            systemctl restart unbound 2>/dev/null || true
        """)
        self._wait_dns_reachable(dns_ip)

    def _wait_dns_reachable(self, dns_ip, timeout=10):
        """Poll until *dns_ip* answers a DNS query from this container."""
        if self.bash("which dig", check=False) is None:
            self.bash(
                "DEBIAN_FRONTEND=noninteractive "
                "apt-get install -y dnsutils 2>/dev/null || true"
            )
        deadline = time.time() + timeout
        while time.time() < deadline:
            result = self.bash(
                f"dig @{dns_ip} . SOA +short +time=1 +tries=1",
                check=False,
            )
            if result and result.strip():
                return
            time.sleep(0.5)
        raise DNSConfigurationError(
            f"DNS at {dns_ip} not reachable from {self.name} after {timeout}s"
        )

    def write_ini(self, disable_ipv6=False):
        """Generate a chatmail.ini config file in lxconfigs/."""
        from chatmaild.config import write_initial_config

        overrides = {
            "max_user_send_per_minute": 600,
            "max_user_send_burst_size": 100,
            "mtail_address": "127.0.0.1",
        }
        if disable_ipv6:
            overrides["disable_ipv6"] = "True"
        write_initial_config(self.ini, self.domain, overrides)
        return self.ini


class DNSContainer(Container):
    """Container handle for the PowerDNS name server.

    Manages the authoritative and recursive DNS services required for
    name resolution in the local testing environment.
    """

    def __init__(self, incus):
        super().__init__(incus, DNS_CONTAINER_NAME, domain=DNS_DOMAIN)

    def pdnsutil(self, *args, check=True):
        """Run ``pdnsutil <args>`` inside the DNS container."""
        return self.run_cmd("pdnsutil", *args, check=check)

    def replace_rrset(self, zone, name, rtype, ttl, rdata):
        """Shortcut for ``pdnsutil replace-rrset``."""
        self.pdnsutil("replace-rrset", zone, name, rtype, ttl, rdata)

    def restart_services(self):
        """Restart pdns and pdns-recursor, then wait until DNS is answering."""
        self.bash("""
            systemctl restart pdns
            systemctl restart pdns-recursor || true
        """)
        self._wait_dns_ready()

    def _wait_dns_ready(self, timeout=60):
        """Poll until the recursor answers a query on port 53."""
        deadline = time.time() + timeout
        while time.time() < deadline:
            result = self.bash(
                "dig @127.0.0.1 . SOA +short +time=1 +tries=1",
                check=False,
            )
            if result and result.strip():
                return
            time.sleep(0.5)
        raise DNSConfigurationError(f"DNS recursor not answering after {timeout}s")

    def ensure(self):
        """Create the DNS container with PowerDNS if needed.

        Calls ``super().ensure()`` to create/start the container
        and set up SSH, then installs PowerDNS and configures
        the Incus bridge to use this container as DNS.
        """
        super().ensure()
        self._install_powerdns()
        self.incus.run(
            ["network", "set", "incusbr0", "dns.mode=none"],
            check=False,
        )
        self.incus.run(
            ["network", "set", "incusbr0", f"raw.dnsmasq=dhcp-option=6,{self.ipv4}"],
            check=False,
        )

    def destroy(self):
        """Stop, delete, and reset bridge DNS config."""
        super().destroy()
        self.incus.run(["network", "unset", "incusbr0", "dns.mode"], check=False)
        self.incus.run(["network", "unset", "incusbr0", "raw.dnsmasq"], check=False)

    def _install_powerdns(self):
        """Install and configure PowerDNS if not already present."""
        if self.run_cmd("which", "pdns_server", check=False) is not None:
            return

        self.bash("""
            systemctl disable --now systemd-resolved 2>/dev/null || true
            rm -f /etc/resolv.conf
            echo 'nameserver 9.9.9.9' > /etc/resolv.conf

            # Block automatic service startup during package installation
            printf '#!/bin/sh\\nexit 101\\n' > /usr/sbin/policy-rc.d
            chmod +x /usr/sbin/policy-rc.d

            apt-get -o DPkg::Lock::Timeout=60 update
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
                pdns-server pdns-backend-sqlite3 sqlite3 pdns-recursor dnsutils

            # Remove the startup block
            rm /usr/sbin/policy-rc.d

            systemctl stop pdns pdns-recursor || true
            mkdir -p /var/lib/powerdns
            sqlite3 /var/lib/powerdns/pdns.sqlite3 \
                </usr/share/doc/pdns-backend-sqlite3/schema.sqlite3.sql
            chown -R pdns:pdns /var/lib/powerdns
        """)

        self.push_file_content(
            "/etc/powerdns/pdns.conf",
            """
            launch=gsqlite3
            gsqlite3-database=/var/lib/powerdns/pdns.sqlite3
            local-address=127.0.0.1
            local-port=5353
            """,
        )

        self.push_file_content(
            "/etc/powerdns/recursor.conf",
            """
            local-address=0.0.0.0
            local-port=53
            forward-zones=localchat=127.0.0.1:5353
            forward-zones-recurse=.=9.9.9.9;149.112.112.112
            allow-from=0.0.0.0/0
            dont-query=
            dnssec=off
            """,
        )

        self.bash("""
            systemctl start pdns
            systemctl start pdns-recursor
            echo 'nameserver 127.0.0.1' > /etc/resolv.conf
        """)
        self._wait_dns_ready()

    def reset_dns_records(self, dns_ip, domains):
        """Create DNS zones with initial A records via pdnsutil.

        Only sets SOA, NS, and A records as the minimal set
        needed for SSH connectivity.  Full records (MX, TXT, SRV,
        CNAME, DKIM) are added later by ``cmdeploy dns``.

        Args:
            dns_ip: IP of the DNS container
            domains: list of dicts with 'name', 'domain', 'ip'
        """
        for d in domains:
            domain = d["domain"]
            ip = d["ip"]
            self.out.print(f"  {domain} -> {ip}")

            # Delete and recreate zone fresh (removes stale records)
            self.pdnsutil("delete-zone", domain, check=False)
            self.pdnsutil("create-zone", domain, f"ns.{domain}")

            serial = str(int(time.time()))
            soa = f"ns.{domain} hostmaster.{domain} {serial} 3600 900 604800 300"
            self.replace_rrset(domain, ".", "SOA", "3600", soa)
            self.replace_rrset(domain, ".", "NS", "3600", f"ns.{domain}.")
            self.replace_rrset(domain, ".", "A", "3600", ip)
            self.replace_rrset(domain, "ns", "A", "3600", dns_ip)

            # AAAA (domain -> container IPv6, if available)
            ipv6 = d.get("ipv6")
            if ipv6:
                self.replace_rrset(domain, ".", "AAAA", "3600", ipv6)
                self.out.print(f"    zone reset: SOA, NS, A, AAAA  ({ip}, {ipv6})")
            else:
                # Remove any stale AAAA record
                self.pdnsutil("delete-rrset", domain, ".", "AAAA", check=False)
                self.out.print(f"    zone reset: SOA, NS, A  ({ip}, IPv4-only)")

        self.restart_services()

    def set_dns_records(self, text):
        """Add or overwrite DNS records from standard BIND format.

        Uses ``cmdeploy.dns.parse_zone_records`` to parse.
        Zones are created automatically from the record names.
        """
        from ..dns import parse_zone_records

        zones_seen = set()

        for name, ttl, rtype, rdata in parse_zone_records(text):
            # Derive zone from name: find top-level .localchat domain
            name_parts = name.split(".")
            zone = name  # fallback
            for i in range(len(name_parts) - 1):
                if name_parts[i + 1 :] == ["localchat"]:
                    zone = ".".join(name_parts[i:])
                    break

            # Create zone if first time seeing it
            if zone not in zones_seen:
                self.pdnsutil(
                    "create-zone",
                    zone,
                    f"ns.{zone}",
                    check=False,
                )
                zones_seen.add(zone)

            # Figure out the record name relative to zone
            if name == zone:
                relative = "."
            elif name.endswith(f".{zone}"):
                relative = name[: -(len(zone) + 1)]
            else:
                relative = name

            self.replace_rrset(zone, relative, rtype, ttl, rdata)

        if zones_seen:
            self.restart_services()
