log_destination = syslog
log_level = info

canonicalization = relaxed/simple

lookup_timeout = 60s

signing_keys = /etc/dkim-milter/signing-keys
signing_senders = /etc/dkim-milter/signing-senders

# Signing
sign_headers = default; autocrypt:content-type
oversign_headers = signed-extended

# Verification
required_signed_headers = From*
forbid_unsigned_content = yes
reject_failures = missing, no-pass, author-mismatch

socket = unix:/var/spool/postfix/dkim-milter/dkim-milter.sock
