log_desintation = syslog
log_level = info

canonicalization = relaxed/simple

lookup_timeout = 60s

signing_keys = /etc/dkim-milter/signing-keys
signing_senders = /etc/dkim-milter/signing-senders

reject_failures = missing, no-pass, author-mismatch

sign_headers = default; autocrypt:content-type
oversign_headers = from:reply-to:subject:date:to:cc:resent-date:resent-from:resent-sender:resent-to:resent-cc:in-reply-to:references:list-id:list-help:list-unsubscribe:list-subscribe:list-post:list-owner:list-archive:autocrypt

socket = unix:/var/spool/postfix/dkim-milter/dkim-milter.sock
