on:
  release:
    types: [published]

jobs:
  build:
    name: Build binaries.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: stable
          targets: aarch64-unknown-linux-musl,x86_64-unknown-linux-musl
      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2
      - uses: taiki-e/install-action@9e1e5806d4a4822de933115878265be9aaa786d9 # v2
        with:
          tool: cargo-zigbuild
      - name: Build
        run: |
          RUSTFLAGS="-Ctarget-feature=+crt-static -Clink-self-contained=yes" \
          cargo zigbuild \
            --release \
            --target x86_64-unknown-linux-musl \
            --target aarch64-unknown-linux-musl
      - name: Upload x86_64 binary
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: filtermail-x86_64
          path: target/x86_64-unknown-linux-musl/release/filtermail
          if-no-files-found: error
      - name: Upload aarch64 binary
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: filtermail-aarch64
          path: target/aarch64-unknown-linux-musl/release/filtermail
          if-no-files-found: error

  publish:
    name: Upload binaries to the release
    needs: ["build"]
    runs-on: ubuntu-latest
    steps:
      - name: Download aarch64 binary
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: filtermail-x86_64
          path: filtermail-x86_64
      - name: Download x86_64 binary
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: filtermail-aarch64
          path: filtermail-aarch64
      - name: Upload binaries to the GitHub release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          REF_NAME: ${{ github.ref_name }}
        run: |
          mkdir dist
          mv filtermail-x86_64/filtermail dist/filtermail-x86_64
          mv filtermail-aarch64/filtermail dist/filtermail-aarch64
          gh release upload "$REF_NAME" \
            --repo ${{ github.repository }} \
            dist/*
