name: deploy on allocated VPS and run tests

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'scripts/**'
      - '**/README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'

jobs:
  deploy-and-test:
    name: deploy on allocated VPS, and run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: prepare SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.STAGING_SSH_KEY }}" >> ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - run: |
          git clone https://github.com/chatmail/hetzner-relay ../hetzner-relay
          pip install ../hetzner-relay
          python3 ../hetzner-relay/main.py --dns --test --rebuild --run-id $GITHUB_RUN_ID --domain2 chatmail-ci.testrun.org .

