name: deploy on allocated VPS and run tests

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'scripts/**'
      - '**/README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'

jobs:
  deploy-and-test:
    name: deploy on allocated VPS, and run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          repository: chatmail/hetzner-relay
          path: hetzner-relay

      - uses: actions/checkout@v4
        with:
          path: relay

      - name: prepare SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.STAGING_SSH_KEY }}" >> ~/.ssh/staging.testrun.org
          chmod 600 ~/.ssh/staging.testrun.org

      - run: pip install hetzner-relay/

      - run: python3 hetzner-relay/main.py --dns --test --rebuild --run-id $GITHUB_RUN_ID --domain2 ci-chatmail.testrun.org --hetzner-api-token ${{ secrets.HETZNER_API_TOKEN }} relay/

